# Travis CI configuration for mkmimo
language: c
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - coreutils
    - bc
    - grep
    - sed
    - mawk
    - pv

install:
- make

script:
- make test
